name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Building ...'
      uses: reuixiy/hugo-deploy@v1
      env:
        DEPLOY_REPO: harriseldon/hugo_blog
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        CNAME: harriseldon.github.io
        DEPLOY_BRANCH: blog
