name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.145.0
        TARGET_REPO: harriseldon/hugo_blog
        TOKEN: ${{ secrets.TOKEN }}
        CNAME: harriseldon.github.io
        HUGO_EXTENDED: true
        HUGO_PUBLISH_DIR: docs
        HUGO_ARGS: '--gc'
